Repository vapor/fluent-mongo-driver, pull requests merged in 2020-05, with the labels that each got.

#25 Fix breaking change in MongoKitten
  Package.swift
  Sources/FluentMongoDriver/MongoDB+Aggregate.swift
  Sources/FluentMongoDriver/MongoDB+Delete.swift
  Sources/FluentMongoDriver/MongoDB+Update.swift
Labels: semver-patch

#26 Register Multiple Databases for FluentBenchmarker Tests
  Package.swift
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: bug

#27 Removed '.' from FluentKit Dependency Version Identifier
  Package.swift
Labels: bug

#28 FluentKit 1.0.0 GM
  .github/workflows/test.yml
  Package.swift
  Sources/FluentMongoDriver/Document+DatabaseOutput.swift
  Sources/FluentMongoDriver/FieldKey+Mongo.swift
  Sources/FluentMongoDriver/MongoDB+DatabaseRow.swift
  Sources/FluentMongoDriver/MongoDB+Schema.swift
  Sources/FluentMongoDriver/MongoDB+Transaction.swift
  Sources/FluentMongoDriver/MongoDB.swift
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
  docker-compose.yml
Labels: enhancement, semver-major

#29 Make the tests run with more threads
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: enhancement
