Repository vapor/fluent-mongo-driver, pull requests merged in 2020-03, with the labels that each got.

#10 Hop the MongoKitten objects to the FluentKit DatabaseContext's EventLoop
  Sources/FluentMongoDriver/MongoDB.swift
Labels: bug

#11 Hop to the Fluent EventLoop in custom MongoDB requests
  Sources/FluentMongoDriver/MongoDB+Aggregate.swift
  Sources/FluentMongoDriver/MongoDB+Delete.swift
  Sources/FluentMongoDriver/MongoDB+Schema.swift
  Sources/FluentMongoDriver/MongoDB+Update.swift
Labels: semver-patch

#14 Implement inverse subset filter with `$nin`
  Sources/FluentMongoDriver/Filter.swift
Labels: bug, semver-patch

#13 Better error handling during test setup and teardown
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: enhancement

#15 Support ObjectId as custom identifier type
  Sources/FluentMongoDriver/Exports.swift
  Sources/FluentMongoDriver/ObjectId+RandomGeneratable.swift
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: enhancement, semver-minor

#17 Add a date en/decoding test
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: enhancement

#19 Fix join and joinCount returning invalid results on queries where a limit is applied
  Sources/FluentMongoDriver/MongoDB+Join.swift
  Tests/FluentMongoDriverTests/FluentMongoDriverTests.swift
Labels: bug, semver-patch

#20 Updates to CI config
  .github/workflows/test.yml
Labels: enhancement
